--1
SELECT COUNT(EMPLOYEE_ID) FROM HR.EMPLOYEES ;
---2---
SELECT D.DEPARTMENT_NAME,COUNT(E.EMPLOYEE_ID)
FROM HR.EMPLOYEES E
JOIN HR.DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;
----3----
SELECT L.CITY, COUNT(E.EMPLOYEE_ID) AS "TOTAL" FROM HR.EMPLOYEES E 
JOIN HR.DEPARTMENTS D on E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN HR.LOCATIONS L on D.LOCATION_ID = L.LOCATION_ID
GROUP BY L.CITY;
---4---
SELECT C.COUNTRY_NAME, COUNT(E.EMPLOYEE_ID) AS "TOTAL" 
FROM HR.EMPLOYEES E 
JOIN HR.DEPARTMENTS D on E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN HR.LOCATIONS L on D.LOCATION_ID = L.LOCATION_ID
JOIN HR.COUNTRIES C on L.COUNTRY_ID = C.COUNTRY_ID
GROUP BY C.COUNTRY_NAME;
---5
SELECT R.REGION_NAME,count(E.EMPLOYEE_ID)
FROM HR.EMPLOYEES E 
JOIN HR.DEPARTMENTS D on E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN HR.LOCATIONS L on D.LOCATION_ID = L.LOCATION_ID
JOIN HR.COUNTRIES C on L.COUNTRY_ID = C.COUNTRY_ID
JOIN HR.REGIONS R on C.REGION_ID = R.REGION_ID
GROUP BY R.REGION_NAME;

select TO_CHAR(e.HIRE_DATE,'YYYY' ), TO_CHAR(e.HIRE_DATE,'MM' ), count(e.EMPLOYEE_ID)
from HR.EMPLOYEES e 
group by TO_CHAR(e.HIRE_DATE,'YYYY' ), TO_CHAR(e.HIRE_DATE,'MM' ) 
order by 1,2;

--7.
select TO_CHAR(e.HIRE_DATE,'YYYY') as year,count(e.EMPLOYEE_ID)
from HR.EMPLOYEES e 
group by TO_CHAR(e.HIRE_DATE,'YYYY' )
order by year asc;

--8
CREATE TABLE DIM_HIREDATE(
   HIREDATE_ID  NUMBER(6) PRIMARY KEY,
   YEAR      NUMBER(4) NOT NULL,
   MONTH     VARCHAR2(10) NOT NULL 
) ;

CREATE TABLE DIM_DEPARTMENT (
   DEPARTMENT_ID  NUMBER(4) PRIMARY KEY,
   REGION      VARCHAR2(30) NOT NULL,
   COUNTRY     VARCHAR2(40) NOT NULL,
   CITY        VARCHAR2(30) NOT NULL,
   DEPARTMENT_NAME   VARCHAR2(30) NOT NULL
) ;

CREATE TABLE FACT_EMP (
   HIREDATE_ID  NUMBER(6) REFERENCES DIM_HIREDATE,
   DEPARTMENT_ID NUMBER(4) REFERENCES DIM_DEPARTMENT,
   NUM_EMP      NUMBER NOT NULL,
   CONSTRAINT FACT_EMP_PK PRIMARY KEY(HIREDATE_ID,DEPARTMENT_ID)
) ;


INSERT INTO  DIM_HIREDATE  
      SELECT  TO_NUMBER(TO_CHAR(HIRE_DATE,'YYYYMM')) AS HIREDATE_ID, 
 		TO_NUMBER(TO_CHAR(HIRE_DATE,'YYYY')) AS YEAR,
TO_CHAR(HIRE_DATE,'MON-YYYY') AS MONTH
             FROM   HR.EMPLOYEES  
      GROUP BY  TO_NUMBER(TO_CHAR(HIRE_DATE,'YYYYMM')), 
 		TO_NUMBER(TO_CHAR(HIRE_DATE,'YYYY')),
                             TO_CHAR(HIRE_DATE,'MON-YYYY')
             ORDER BY 1 ;

COMMIT ;

SELECT * FROM DIM_HIREDATE ;

SELECT * FROM DiM_DEPARTMENT ;

INSERT INTO DIM_DEPARTMENT
SELECT DEPARTMENT_ID, R.REGION_NAME, COUNTRY_NAME, CITY, DEPARTMENT_NAME
FROM HR.DEPARTMENTS D JOIN HR.LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID 
   JOIN HR.COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
   JOIN HR.REGIONS R ON C.REGION_ID = R.REGION_ID
ORDER BY 1 ;

SELECT * FROM DIM_DEPARTMENT ;


INSERT INTO FACT_EMP
      SELECT   TO_NUMBER(TO_CHAR(HIRE_DATE,'YYYYMM')),
                      DEPARTMENT_ID,
                      COUNT(EMPLOYEE_ID)
             FROM   HR.EMPLOYEES
             WHERE  DEPARTMENT_ID IS NOT NULL
             GROUP BY  TO_NUMBER(TO_CHAR(HIRE_DATE,'YYYYMM')), DEPARTMENT_ID ;
             
COMMIT ;

SELECT SUM(NUM_EMP) FROM FACT_EMP;

--16
SELECT D.REGION , SUM(NUM_EMP) FROM FACT_EMP E
JOIN DIM_DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
GROUP BY D.REGION;

--15.
SELECT D.COUNTRY , SUM(NUM_EMP) FROM FACT_EMP E
JOIN DIM_DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
GROUP BY D.COUNTRY;

--14.
SELECT D.COUNTRY,D.CITY , SUM(NUM_EMP) FROM FACT_EMP E
JOIN DIM_DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
GROUP BY D.COUNTRY, D.CITY;

--13
SELECT D.DEPARTMENT_NAME , SUM(NUM_EMP) FROM FACT_EMP E
JOIN DIM_DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
GROUP BY D.DEPARTMENT_NAME;

--17
SELECT H.MONTH, SUM(NUM_EMP) 
FROM FACT_EMP E JOIN DIM_HIREDATE H ON E.HIREDATE_ID=H.HIREDATE_ID
GROUP BY H.MONTH;


--18
SELECT H.YEAR, SUM(NUM_EMP) 
FROM FACT_EMP E JOIN DIM_HIREDATE H ON E.HIREDATE_ID=H.HIREDATE_ID
GROUP BY H.YEAR;